services:
  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9093:9092"

  # Master HDFS (NameNode)
  unircluster-m:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: unircluster-m
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://unircluster-m:9000
    ports:
      - "9870:9870"   # HDFS NameNode UI
    volumes:
      - ./hadoop/name:/hadoop/dfs/name
    command: ["namenode"]

  # Worker 0 (DataNode)
  unircluster-w-0:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: unircluster-w-0
    depends_on:
      - unircluster-m
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://unircluster-m:9000
    volumes:
      - ./hadoop/data0:/hadoop/dfs/data
    command: ["datanode"]

  # Worker 1 (DataNode)
  unircluster-w-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: unircluster-w-1
    depends_on:
      - unircluster-m
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://unircluster-m:9000
    volumes:
      - ./hadoop/data1:/hadoop/dfs/data
    command: ["datanode"]

  # Spark Master
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "7077:7077"   # Spark master endpoint
      - "8080:8080"   # Spark master UI
    depends_on:
      - unircluster-m

  # Spark Worker
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  # JupyterLab para PySpark
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
    command: >
      start-notebook.sh --NotebookApp.token=''

networks:
  default:
    driver: bridge